cloudlogin:
    type:     rest
    resource: ITG\CloudBundle\Controller\CloudController

validateBenificiary:
    type:     rest
    resource: ITG\CloudBundle\Controller\CloudController

createConversion:
    type:     rest
    resource: ITG\CloudBundle\Controller\CloudController
    
findPayment:
    type:     rest
    resource: ITG\CloudBundle\Controller\PaymentCloudController
