cloudlogin:
    type:     rest
    resource: ITG\CloudBundle\Controller\CloudController

validateBenificiary:
    type:     rest
    resource: ITG\CloudBundle\Controller\CloudController

createConversion:
    type:     rest
    resource: ITG\CloudBundle\Controller\CloudController

cloudCurrency:
    type:     rest
    resource: ITG\CloudBundle\Controller\CloudController

cloudConversionDates:
    type:     rest
    resource: ITG\CloudBundle\Controller\CloudController

cloudPaymentDates:
    type:     rest
    resource: ITG\CloudBundle\Controller\CloudController
