<?php

namespace ITG\LogBundle\Repository;

use AppBundle\Repository\PaginatedRepository;
use ITG\LogBundle\Model\LogList;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends PaginatedRepository
{
    protected $modelClass = LogList::class;
}
