<?php

namespace AppBundle\Repository;

/**
 * W2CheckRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class W2CheckBeneficiaryRepository extends \Doctrine\ORM\EntityRepository
{
}
