<?php

namespace Somtel\PipBundle\Repository;

use AppBundle\Entity\User;

/**
 * PipCashinOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PipCashinOrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByUser(User $user)
    {
        $qb = $this->createQueryBuilder('t');
        $qb->select('t')->where('t.user = :user')->setParameter('user', $user);
        return $qb->getQuery()->getResult();
    }
}
