<?php

namespace Somtel\WoraPayBundle\Repository;

/**
 * CardTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
