<?php

namespace ITG\UserBundle\Repository;

use ITG\MillBundle\Repository\PaginatedRepository;
use ITG\UserBundle\Model\UserList;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends PaginatedRepository
{
    protected $modelClass = UserList::class;
}
