validateCustomer:
    type:     rest
    resource: ITG\DahabBundle\Controller\DahabController

processPayment:
    type:     rest
    resource: ITG\DahabBundle\Controller\DahabController

sendSMS:
    type:     rest
    resource: ITG\DahabBundle\Controller\DahabController
