<?php

namespace ITG\JumioBundle\Repository;
use ITG\JumioBundle\Entity\Netverify;

/**
 * NetverifyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NetverifyRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Select unfulfilled Netverify record or create a new one if other ones are fulfilled or not found
     *
     * @param $userReference string Remit One user reference
     *
     * @return Netverify|null
     */
    public function findOrCreate($userReference)
    {
        $qb = $this->createQueryBuilder('t');
        $qb->select('t')
            ->where('t.photoFront IS NULL OR t.photoBack IS NULL OR t.photoFace IS NULL')
            ->andWhere('t.response IS NULL')
            ->andWhere('t.sent IS NULL')
            ->andWhere('t.userReference = :ur')->setParameter('ur', $userReference)
        ;

        $res = $qb->getQuery()->getOneOrNullResult();

        if(!$res)
        {
            $res = new Netverify();
            $res->setUserReference($userReference);
            $this->getEntityManager()->persist($res);
        }

        return $res;
    }
}
