<?php

namespace ITG\JumioBundle\Repository;

/**
 * NetverifyResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NetverifyResponseRepository extends \Doctrine\ORM\EntityRepository
{
}
